# 一些配置教程
# https://squidfunk.github.io/mkdocs-material
# https://www.mkdocs.org
# https://zhuanlan.zhihu.com/p/383582472
# https://markdown-docs-zh.readthedocs.io/zh-cn/latest
# https://docs.netlify.com/frameworks/#mkdocs
# https://www.starfallprojects.co.uk/projects/deploy-host-docs/deploy-mkdocs-material-vercel/

site_name: SD Note

theme:
  name: material
  language: zh
  features:
    # - navigation.instant # 即时加载, 在firefox下有内存泄露的问题
    - navigation.instant.prefetch # 即时预加载
    - navigation.instant.progress # 加载进度显示
    - navigation.instant.preview # 即时预览
    - navigation.tracking # 锚点跟踪
    - navigation.tabs # 导航选项卡
    - navigation.tabs.sticky # 始终显示导航选项卡
    - navigation.path # 显示导航路径
    # - navigation.prune # 导航修剪
    # - navigation.indexes # 章节索引页
    - navigation.expand # 侧边栏展开
    - navigation.footer # 启用页脚
    - navigation.top # 返回顶部按钮
    - search.suggest # 搜索建议
    - search.highlight # 搜索高亮
    - search.share # 搜索共享
    - content.action.edit # 编辑本页按钮
    # - content.action.view # 查看本页源代码
    - content.code.copy # 代码块复制按钮
    - content.code.annotate # 代码注解
    - content.tabs.link # 链接的内容选项卡
    - content.tooltips # 改进的工具提示
    
  palette: # 颜色

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 跟随系统配色

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default # 配色
      primary: white # 原色
      accent: light blue # 强调色
      toggle:
        icon: material/brightness-7
        name: 浅色主题

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: 黑暗主题

  logo: assets/site_resources/logo.png
  favicon: assets/site_resources/favicon.png

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

plugins:
  - search # 搜索功能
  - tags # 标签插件
  - git-revision-date-localized:
      enable_creation_date: false # 显示与页面关联的文件的创建日期
      type: iso_date # 时间格式
  - glightbox # 图像缩放
#  - git-committers:
#      repository: licyk/SDNote
#      branch: main
#  - git-authors

extra:
  homepage: https://sdnote.netlify.app
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/licyk
      name: Github
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/46497516
      name: 哔哩哔哩
    - icon: fontawesome/solid/blog
      link: https://licyk.netlify.app
      name: licyk的小窝
    - icon: fontawesome/solid/envelope
      link: mailto:licyk233@163.com
      name: 联系邮箱

  generator: false # 生成器通知

copyright: Copyright &copy; 2024 licyk

repo_url: https://github.com/licyk/SDNote
repo_name: licyk/SDNote
edit_uri: edit/main/docs/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex
  - pymdownx.b64
  - pymdownx.betterem
  - pymdownx.blocks.admonition
  - pymdownx.blocks.definition
  - pymdownx.blocks.details
  - pymdownx.blocks.html
  - pymdownx.blocks.tab
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.escapeall
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.pathconverter
  - pymdownx.progressbar
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.striphtml
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr
  - admonition
  - toc:
      # permalink: true
      # permalink: ↗ ⬈ ⇗ ➶ ➹ 🡥 🡵 🡽 🢅 ⬈ ⬀ ⭷ 🛪 ⧉ ⧉ ⮺ ⎋ ⏍ ◳ ❐ ⬔ ⭷ ↸ ⇱ ⤯ ↻ ⇲ ⎘ 🔗
      permalink: ☍
      permalink_title: 锚链接到此处
      title: 目录
  - tables

nav:
- "主页": index.md
- "部署与使用":
  - guide/index.md
  - "需求与准备":
    - guide/requirement/index.md
  - "模型指南":
    - guide/model/index.md
    - "模型下载": guide/model/download_model.md
  - "SD WebUI 部署与使用":
    - "概述": guide/sd_webui/index.md
    - "部署": guide/sd_webui/install.md
    - "文生图": guide/sd_webui/t2i.md
    - "提示词书写": guide/sd_webui/prompt.md
    - "高级提示词语法": guide/sd_webui/advance_prompt.md
    - "画师提示词应用": guide/sd_webui/artist_prompt.md
    - "图生图": guide/sd_webui/i2i.md
    - "LoRA 应用": guide/sd_webui/lora.md
    - "放大图片": guide/sd_webui/upscale.md
    - "ControlNet 应用": guide/sd_webui/controlnet.md
    - "杂项": guide/sd_webui/extra.md
  - "SD WebUI Forge 部署与使用":
    - "概述": guide/sd_webui_forge/index.md
    - "部署": guide/sd_webui_forge/install.md
    - "常见功能使用": guide/sd_webui_forge/common_use.md
    - "FLUX 模型使用": guide/sd_webui_forge/flux.md
    - "显存优化": guide/sd_webui_forge/video_momory_optimization.md
    - "内置扩展使用": guide/sd_webui_forge/use_build_in_extension.md
  - "ComfyUI 部署与使用":
    - "概述": guide/comfyui/index.md
    - "部署": guide/comfyui/install.md
    - "界面操作": guide/comfyui/interface_operation.md
    - "搭建工作流": guide/comfyui/build_workflow.md
    - "使用导入工作流": guide/comfyui/input_workflows.md
    - "杂项": guide/comfyui/extra.md
    - "节点库":
      - "概述": guide/comfyui/nodes/index.md
      - "实用工具": guide/comfyui/nodes/utils/index.md
      - "采样":
        - "采样": guide/comfyui/nodes/sampling/index.md
        - "自定义采样":
          - "自定义采样": guide/comfyui/nodes/sampling/custom_sampling/index.md
          - "调度器": guide/comfyui/nodes/sampling/custom_sampling/schedulers/index.md
          - "采样器": guide/comfyui/nodes/sampling/custom_sampling/samplers/index.md
          - "Sigmas": guide/comfyui/nodes/sampling/custom_sampling/sigmas/index.md
          - "引导器": guide/comfyui/nodes/sampling/custom_sampling/guiders/index.md
          - "噪波": guide/comfyui/nodes/sampling/custom_sampling/noise/index.md
        - "视频模型": guide/comfyui/nodes/sampling/video_models/index.md
      - "加载器":
        - "加载器": guide/comfyui/nodes/loaders/index.md
        - "视频模型": guide/comfyui/nodes/loaders/video_models/index.md
      - "条件":
        - "条件": guide/comfyui/nodes/conditioning/index.md
        - "风格模型": guide/comfyui/nodes/conditioning/style_model/index.md
        - "ControlNet": guide/comfyui/nodes/conditioning/controlnet/index.md
        - "GLIGEN": guide/comfyui/nodes/conditioning/gligen/index.md
        - "内补": guide/comfyui/nodes/conditioning/inpaint/index.md
        - "视频模型": guide/comfyui/nodes/conditioning/video_models/index.md
        - "3D 模型": guide/comfyui/nodes/conditioning/3d_models/index.md
        - "放大扩散": guide/comfyui/nodes/conditioning/upscale_diffusion/index.md
        - "StableCascade": guide/comfyui/nodes/conditioning/stable_cascade/index.md
        - "InstructPix2Pix": guide/comfyui/nodes/conditioning/instructpix2pix/index.md
      - "Latent":
        - "Latent": guide/comfyui/nodes/latent/index.md
        - "内补": guide/comfyui/nodes/latent/inpaint/index.md
        - "批处理": guide/comfyui/nodes/latent/batch/index.md
        - "变换": guide/comfyui/nodes/latent/transform/index.md
        - "高级":
          - "高级": guide/comfyui/nodes/latent/advanced/index.md
          - "operations": guide\comfyui\nodes\latent\advanced\operations\index.md
        - "StableCascade": guide/comfyui/nodes/latent/stable_cascade/index.md
        - "音频": guide/comfyui/nodes/latent/audio/index.md
        - "SD3": guide/comfyui/nodes/latent/sd3/index.md
        - "video":
          - "video": guide/comfyui/nodes/latent/video/index.md
          - "ltxv": guide/comfyui/nodes/latent/video/ltxv/index.md
      - "图像":
        - "图像": guide/comfyui/nodes/image/index.md
        - "放大": guide/comfyui/nodes/image/upscaling/index.md
        - "后处理": guide/comfyui/nodes/image/postprocessing/index.md
        - "批处理": guide/comfyui/nodes/image/batch/index.md
        - "预处理": guide/comfyui/nodes/image/preprocessors/index.md
        - "变换": guide/comfyui/nodes/image/transform/index.md
        - "动画": guide/comfyui/nodes/image/animation/index.md
      - "遮罩":
        - "遮罩": guide/comfyui/nodes/mask/index.md
        - "合成": guide/comfyui/nodes/mask/compositing/index.md
      - "测试":
        - "测试": guide/comfyui/nodes/_for_testing/index.md
        - "自定义采样": guide/comfyui/nodes/_for_testing/custom_sampling/noise/index.md
        - "条件": guide/comfyui/nodes/_for_testing/conditioning/index.md
        - "StableCascade": guide/comfyui/nodes/_for_testing/stable_cascade/index.md
        - "注意力测试": guide/comfyui/nodes/_for_testing/attension_experiments/index.md
      - "高级":
        - "高级": guide/comfyui/nodes/advanced/index.md
        - "加载器": guide/comfyui/nodes/advanced/loaders/index.md
        - "条件":
          - "条件": guide/comfyui/nodes/advanced/conditioning/index.md
          - "flux": guide/comfyui/nodes/advanced/conditioning/flux/index.md
        - "模型融合":
          - "模型融合": guide/comfyui/nodes/advanced/model_merging/index.md
          - "模型版本": guide/comfyui/nodes/advanced/model_merging/model_specific/index.md
        - "模型": guide/comfyui/nodes/advanced/model/index.md
        - "guidance": guide/comfyui/nodes/advanced/guidance/index.md
        - "hooks":
          - "hooks": guide/comfyui/nodes/advanced/hooks/index.md
          - "create": guide/comfyui/nodes/advanced/hooks/create/index.md
          - "调度": guide/comfyui/nodes/advanced/hooks/scheduling/index.md
          - "combine": guide/comfyui/nodes/advanced/hooks/combine/index.md
          - "cond single": guide/comfyui/nodes/advanced/hooks/cond_single/index.md
          - "cond pair": guide/comfyui/nodes/advanced/hooks/cond_pair/index.md
          - "CLIP": guide/comfyui/nodes/advanced/hooks/clip/index.md
      - "模型微调":
        - "UNet": guide/comfyui/nodes/model_patches/unet/index.md
      - "音频": guide/comfyui/nodes/audio/index.md
      - "api":
        - "图像": guide/comfyui/nodes/api/image/index.md
- "绘世启动器使用":
  - sd_launcher/index.md
  - "部署功能":
    - sd_launcher/install/index.md
  - "高级选项":
    - "高级选项": sd_launcher/advance/index.md
    - "环境维护": sd_launcher/advance/env.md
    - "补丁管理": sd_launcher/advance/patch.md
  - "版本管理":
    - sd_launcher/ver_manager/index.md
    - "内核": sd_launcher/ver_manager/kernel.md
    - "扩展": sd_launcher/ver_manager/extension.md
    - "安装新扩展": sd_launcher/ver_manager/install.md
  - "实用功能":
    - "疑难解答": sd_launcher/other/faq.md
    - "模型管理": sd_launcher/other/model.md
    - "控制台": sd_launcher/other/terminal.md
    - "启动器设置": sd_launcher/other/setting.md
    - "配置 ZLUDA": sd_launcher/other/zluda.md
    - "杂项": sd_launcher/other/index.md
- "使用疑难解答":
  - help/index.md
  - "绘世启动器": help/sd_launcher.md
  - "SD WebUI": help/sd_webui.md
  - "ComfyUI": help/comfyui.md
  - "其他问题": help/other.md
  - "AMD 运行问题": help/amd_info.md
  - "Intel 运行问题": help/intel_info.md
- "附录": appendix.md
- "关于": about.md
